### ISSUE TITLE
Can't give android directory file permissions

### ISSUE THREAD

**Issue by Stunam1** [ComputerElite/QuestAppVersionSwitcher#62] opened 2024-03-31 08:21 UTC
since latest quest 2 version, you can't give android directory file permissions, when trying it says "Can't use this folder. To protect your privacy, use another folder." this stops you from doing basically anything

**Comment by ComputerElite** [comment] 2024-03-31 08:35
Duplicate of #59

**Closed by ComputerElite** 2024-03-31 08:35 UTC
